"""Pure analytics package for imported or explicitly authorized market data."""

from gaijin_market_analytics.backtesting import (
    CalibrationCaseStatus,
    CalibrationCohortSummary,
    CalibrationExitReason,
    CalibrationSkipReason,
    CalibrationSplit,
    ComponentCorrelation,
    HistoricalTradeBucket,
    HistoricalTradeGranularity,
    ItemHistoricalTradeHistory,
    ItemMarketHistory,
    OpportunityCalibrationCase,
    OpportunityCalibrationConfig,
    OpportunityCalibrationResult,
    ScoreBinSummary,
    TemporalSplitConfig,
    TradeEvidenceCalibrationResult,
    TradeEvidenceCase,
    TradeEvidenceCohortSummary,
    TradeEvidenceConfig,
    TradeEvidenceLevel,
    TradeEvidenceSegmentDimension,
    TradeEvidenceSegmentSummary,
    TradeEvidenceView,
    TradeLiquidityBand,
    TradeMarketPhase,
    generate_calibration_cutoffs,
    run_opportunity_calibration,
)
from gaijin_market_analytics.contracts import AnalysisRequest, AnalysisResult, MarketObservation
from gaijin_market_analytics.enums import AnalysisHorizon, AnalysisStatus, ReasonCode
from gaijin_market_analytics.fees import GAIJIN_MARKET_FEE_POLICY_V1, FeePolicy
from gaijin_market_analytics.market_rules import GAIJIN_MARKET_RULES_V1, MarketRules
from gaijin_market_analytics.opportunities import (
    OpportunityScoreConfig,
    OpportunityScoreResult,
    OpportunityScoreV1,
    RankedOpportunityScore,
    rank_opportunity_scores,
)
from gaijin_market_analytics.strategies.rule_based_v1 import RuleBasedV1, RuleBasedV1Config

__all__ = [
    "AnalysisHorizon",
    "AnalysisRequest",
    "AnalysisResult",
    "AnalysisStatus",
    "CalibrationCaseStatus",
    "CalibrationCohortSummary",
    "CalibrationExitReason",
    "CalibrationSkipReason",
    "CalibrationSplit",
    "ComponentCorrelation",
    "HistoricalTradeBucket",
    "HistoricalTradeGranularity",
    "ItemHistoricalTradeHistory",
    "FeePolicy",
    "GAIJIN_MARKET_FEE_POLICY_V1",
    "GAIJIN_MARKET_RULES_V1",
    "ItemMarketHistory",
    "MarketRules",
    "MarketObservation",
    "OpportunityCalibrationCase",
    "OpportunityCalibrationConfig",
    "OpportunityCalibrationResult",
    "OpportunityScoreConfig",
    "OpportunityScoreResult",
    "OpportunityScoreV1",
    "RankedOpportunityScore",
    "rank_opportunity_scores",
    "run_opportunity_calibration",
    "ReasonCode",
    "ScoreBinSummary",
    "TemporalSplitConfig",
    "TradeEvidenceCalibrationResult",
    "TradeEvidenceCase",
    "TradeEvidenceCohortSummary",
    "TradeEvidenceConfig",
    "TradeEvidenceLevel",
    "TradeEvidenceSegmentDimension",
    "TradeEvidenceSegmentSummary",
    "TradeEvidenceView",
    "TradeLiquidityBand",
    "TradeMarketPhase",
    "generate_calibration_cutoffs",
    "RuleBasedV1",
    "RuleBasedV1Config",
]
